package com.tl.booking.gateway.entity.constant;

public interface PrivilegeId {
  String GET_PROMO_LIST = "300";
  String CREATE_PROMO_LIST = "301";
  String UPDATE_PROMO_LIST = "302";
  String REQUEST_APPROVAL_PROMO_LIST = "303";
  String ACTIVATE_PROMO_LIST = "304";
  String UNACTIVATE_PROMO_LIST = "305";
  String DELETE_PROMO_LIST = "306";
  String GET_PROMO_CATEGORY = "310";
  String CREATE_PROMO_CATEGORY = "311";
  String UPDATE_PROMO_CATEGORY = "312";
  String DELETE_PROMO_CATEGORY = "313";
  String MM_MODULE = "207";
  String HOLIDAY = "207";
  String CREATE_IMAGES = "301";

  String CREATE_PROMO_CODE = "320";
  String FIND_BY_ID_PROMO_CODE = "321";
  String GET_PROMO_CODE = "326";
  String ACTIVATE_PROMO_CODE = "322";
  String UNACTIVATE_PROMO_CODE = "323";

  String UPDATE_PROMO_CODE = "324";
  String DELETE_PROMO_CODE = "325";


  String CREATE_CAMPAIGN = "330";
  String FIND_BY_ID_CAMPAIGN = "331";
  String GET_CAMPAIGN = "332";

  String ACTIVATE_CAMPAIGN = "337";
  String UNACTIVATE_CAMPAIGN = "338";
  String PENDING_CAMPAIGN = "336";
  String REJECTED_CAMPAIGN = "339";

  String UPDATE_CAMPAIGN = "333";
  String DELETE_CAMPAIGN = "334";
  String FIND_CAMPAIGN_ACTIVATE = "340";

  String CREATE_PROMO_ADJUSTMENT = "350";
  String FIND_BY_ID_PROMO_ADJUSTMENT = "351";
  String GET_PROMO_ADJUSTMENT = "352";

  String ACTIVATE_PROMO_ADJUSTMENT = "353";
  String UNACTIVATE_PROMO_ADJUSTMENT = "354";
  String PENDING_PROMO_ADJUSTMENT = "355";
  String REJECTED_PROMO_ADJUSTMENT = "357";

  String UPDATE_PROMO_ADJUSTMENT = "358";
  String DELETE_PROMO_ADJUSTMENT = "359";
  String FIND_PROMO_ADJUSTMENT_ACTIVATE = "360";

  String CREATE_VARIABLE = "370";
  String FIND_BY_ID_VARIABLE = "371";
  String GET_VARIABLE = "372";

  String UPDATE_VARIABLE = "373";
  String DELETE_VARIABLE = "374";


  String CREATE_PRODUCT_TYPE = "380";
  String FIND_BY_ID_PRODUCT_TYPE = "381";
  String GET_PRODUCT_TYPE = "382";

  String UPDATE_PRODUCT_TYPE = "383";
  String DELETE_PRODUCT_TYPE = "384";
  String FIND_PRODUCT_TYPE = "385";


  String CREATE_BIN_NUMBER = "390";
  String FIND_BY_ID_BIN_NUMBER = "391";
  String GET_BIN_NUMBER = "392";

  String UPDATE_BIN_NUMBER = "393";
  String DELETE_BIN_NUMBER = "394";
  String FIND_BIN_NUMBER = "395";

  String FIND_ALL_BANK = "400";
  String FIND_ALL_PAYMENT = "410";
  String FIND_ALL_STORE_ID = "420";
  String FIND_ALL_CARD_TYPE = "440";
  String FIND_ALL_VARIABLE = "450";
  String FIND_ALL_CHANNEL_ID = "460";

  String CREATE_BUSINESS_LOGIC_RESPONSE = "470";
  String FIND_BY_ID_BUSINESS_LOGIC_RESPONSE = "471";
  String GET_BUSINESS_LOGIC_RESPONSE = "472";

  String UPDATE_BUSINESS_LOGIC_RESPONSE = "473";
  String DELETE_BUSINESS_LOGIC_RESPONSE = "474";
  String FIND_ALL_BUSINESS_LOGIC_RESPONSE = "475";


  String FIND_VARIABLE_SOURCE = "480";

  String FIND_MARKUP_FLIGHT = "490";
}
