apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: booking-promocode-be
  name: booking-promocode-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: booking-promocode-be
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: booking-promocode-be
    spec:
      containers:
        - name: booking-promocode1
          image: asia.gcr.io/prismatic-fact-201508/booking-promocode-be:latest
          imagePullPolicy: Always
          resources:
          requests:
            memory: "1500Mi"
            cpu: "300m"
          limits:
            memory: "1500Mi"
            cpu: "300m"
          ports:
          - containerPort: 8181
          env:
          - name: SPRING_DATA_MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: promo-secret-config
                key: dbname
          - name: SPRING_DATA_MONGODB_USER
            valueFrom:
              secretKeyRef:
                name: promo-secret-config
                key: username
          - name: SPRING_DATA_MONGODB_PWD
            valueFrom:
              secretKeyRef:
                name: promo-secret-config
                key: password
          volumeMounts:
          - mountPath: /app/config
            name: promo-config
      volumes:
       - configMap:
           defaultMode: 420
           name: promo-config
         name: promo-config

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  labels:
    app: booking-promocode-be
  name: booking-promocode-be-hpa
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: booking-promocode-be
  targetCPUUtilizationPercentage: 30  
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: booking-promocode-be
  name: booking-promocode-be
  namespace: default
spec:
  ports:
    - name: booking-promocode-be
      port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    run: booking-promocode-be
  type: ClusterIP
